[package]
name = "playlist-generator-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[dependencies]
eframe.workspace = true
egui.workspace = true
playlist-generator-core = { version = "=0.9.2", path = "../playlist-generator-core" }
pollster.workspace = true
rfd.workspace = true

[target.'cfg(not(windows))'.dependencies]
eframe = { workspace = true, features = ["wayland", "x11"] }
rfd = { workspace = true, features = ["xdg-portal", "wayland"] }

[dev-dependencies]
egui_kittest.workspace = true

[lints]
workspace = true
