[package]
name = "playlist-generator-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
eframe.workspace = true
egui.workspace = true
playlist-generator-core = { version = "=0.9.1", path = "../playlist-generator-core" }
pollster.workspace = true
rfd.workspace = true

[target.'cfg(windows)'.dependencies]
eframe = { workspace = true, features = ["wgpu_no_default_features"] }
wgpu = { workspace = true, features = ["dx12"] }

[target.'cfg(not(windows))'.dependencies]
eframe = { workspace = true, features = ["glow", "wayland", "x11"] }
rfd = { workspace = true, features = ["xdg-portal", "wayland"] }

[dev-dependencies]
egui_kittest.workspace = true

[lints]
workspace = true
