<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>PlaylistGenerator</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Description>Avalonia desktop interface for Playlist Generator.</Description>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PlaylistGenerator.Core/PlaylistGenerator.Core.csproj" />
    <ProjectReference Include="../PlaylistGenerator.Presentation/PlaylistGenerator.Presentation.csproj" />
  </ItemGroup>

  <Target Name="ExcludeNativeDebugSymbolsFromPublish" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <ResolvedFileToPublish
          Remove="@(ResolvedFileToPublish)"
          Condition="'%(ResolvedFileToPublish.Extension)' == '.pdb'" />
    </ItemGroup>
  </Target>
</Project>
