[build]
rustflags = ["-C", "link-arg=-Wl,-z,relro,-z,now"]

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
rustflags = ["-C", "link-arg=-Wl,--dynamicbase,--nxcompat,--high-entropy-va"]

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-Wl,-z,relro,-z,now"]

[target.aarch64-pc-windows-gnullvm]
linker = "aarch64-w64-mingw32-clang"
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-static",
  "-C", "link-arg=-Wl,--dynamicbase,--nxcompat,--high-entropy-va",
]
