<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>playlist-generator</AssemblyName>
    <RootNamespace>PlaylistGenerator.Cli</RootNamespace>
    <Description>Command-line interface for Playlist Generator.</Description>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PlaylistGenerator.CommandLine/PlaylistGenerator.CommandLine.csproj" />
    <ProjectReference Include="../PlaylistGenerator.Core/PlaylistGenerator.Core.csproj" />
  </ItemGroup>
</Project>
